### ISSUE TITLE
Hydrogen 0.9.5 fails to build with the latest GCC 4.7.1 in Gentoo

### ISSUE THREAD

**Issue by vonamann** [hydrogen-music/hydrogen#36]
GCC 4.6.3 builds successfully.

GCC 4.7.1 gives following error:

```
g++ -o gui/src/SongEditor/SongEditor.o -c -O3 -pipe -DALSA_SUPPORT -DJACK_SUPPORT -DLADSPA_SUPPORT -DLIBARCHIVE_SUPPORT -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_SHARED -I. -Igui/src -I3rdparty/install/include -Ilibs/hydrogen/include -Igui/src/UI -I/usr/include/qt4 -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtXml gui/src/SongEditor/SongEditor.cpp
gui/src/SongEditor/SongEditor.cpp: In member function ‘void SongEditorPatternList::patternPopup_save()’:
gui/src/SongEditor/SongEditor.cpp:1110:17: error: ‘usleep’ was not declared in this scope
scons: *** [gui/src/SongEditor/SongEditor.o] Error 1
scons: building terminated because of errors.
```
