### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by rock-hopper** [hydrogen-music/hydrogen#210]
The latest code in the master branch doesn't compile in AVLinux but does in KXStudio 14.04

Compilation stops at line 26 in tests/xml_test.cpp

`H2Core::InstrumentLayer* layer = instrument->get_layer( n );`

Should this line be something like

`H2Core::InstrumentLayer* layer = instrument->get_component(0)->get_layer( n );`
